package pl.edu.agh.soa2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-04T22:07:25.199+02:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://soa2.agh.edu.pl/", name = "Student")
@XmlSeeAlso({ObjectFactory.class})
public interface Student {

    @WebMethod(action = "addSubject")
    @RequestWrapper(localName = "addSubject", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.AddSubject")
    @ResponseWrapper(localName = "addSubjectResponse", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.AddSubjectResponse")
    @WebResult(name = "ElementsWraper", targetNamespace = "")
    public pl.edu.agh.soa2.AddSubjectResponse.ElementsWraper addSubject(
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject
    );

    @WebMethod(action = "Hello")
    @RequestWrapper(localName = "hello", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.HelloResponse")
    @WebResult(name = "Element", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );

    @WebMethod(action = "addSubject")
    @RequestWrapper(localName = "editSubject", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.EditSubject")
    @ResponseWrapper(localName = "editSubjectResponse", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.EditSubjectResponse")
    @WebResult(name = "ElementsWraper", targetNamespace = "")
    public pl.edu.agh.soa2.EditSubjectResponse.ElementsWraper editSubject(
        @WebParam(name = "filter", targetNamespace = "")
        java.lang.String filter,
        @WebParam(name = "value", targetNamespace = "")
        java.lang.String value,
        @WebParam(name = "operation", targetNamespace = "")
        int operation
    );

    @WebMethod(action = "encodeImage")
    @RequestWrapper(localName = "encodeImage", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.EncodeImage")
    @ResponseWrapper(localName = "encodeImageResponse", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.EncodeImageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String encodeImage(
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName
    );

    @WebMethod(action = "getSubjects")
    @RequestWrapper(localName = "getSubjects", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.GetSubjects")
    @ResponseWrapper(localName = "getSubjectsResponse", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.GetSubjectsResponse")
    @WebResult(name = "ElementsWraper", targetNamespace = "")
    public pl.edu.agh.soa2.GetSubjectsResponse.ElementsWraper getSubjects();

    @WebMethod(action = "addSubject")
    @RequestWrapper(localName = "filterSubjectsContaining", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.FilterSubjectsContaining")
    @ResponseWrapper(localName = "filterSubjectsContainingResponse", targetNamespace = "http://soa2.agh.edu.pl/", className = "pl.edu.agh.soa2.FilterSubjectsContainingResponse")
    @WebResult(name = "ElementsWraper", targetNamespace = "")
    public pl.edu.agh.soa2.FilterSubjectsContainingResponse.ElementsWraper filterSubjectsContaining(
        @WebParam(name = "filter", targetNamespace = "")
        java.lang.String filter
    );
}
