package pl.edu.agh.soa2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-04T22:07:25.283+02:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "StudentService",
                  wsdlLocation = "http://localhost:8080/lab-ejb/Student?wsdl",
                  targetNamespace = "http://soa2.agh.edu.pl/")
public class StudentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soa2.agh.edu.pl/", "StudentService");
    public final static QName StudentPort = new QName("http://soa2.agh.edu.pl/", "StudentPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/lab-ejb/Student?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/lab-ejb/Student?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StudentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Student
     */
    @WebEndpoint(name = "StudentPort")
    public Student getStudentPort() {
        return super.getPort(StudentPort, Student.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Student
     */
    @WebEndpoint(name = "StudentPort")
    public Student getStudentPort(WebServiceFeature... features) {
        return super.getPort(StudentPort, Student.class, features);
    }

}
