package pl.edu.agh.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-14T21:11:28.756+02:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "StudentsManagerService",
                  wsdlLocation = "http://localhost:8080/lab-ejb/StudentsManager?wsdl",
                  targetNamespace = "http://soap.agh.edu.pl/")
public class StudentsManagerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.agh.edu.pl/", "StudentsManagerService");
    public final static QName StudentsManagerPort = new QName("http://soap.agh.edu.pl/", "StudentsManagerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/lab-ejb/StudentsManager?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentsManagerService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/lab-ejb/StudentsManager?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentsManagerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentsManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentsManagerService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StudentsManagerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentsManagerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentsManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StudentsManager
     */
    @WebEndpoint(name = "StudentsManagerPort")
    public StudentsManager getStudentsManagerPort() {
        return super.getPort(StudentsManagerPort, StudentsManager.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentsManager
     */
    @WebEndpoint(name = "StudentsManagerPort")
    public StudentsManager getStudentsManagerPort(WebServiceFeature... features) {
        return super.getPort(StudentsManagerPort, StudentsManager.class, features);
    }

}
